name: meu_primeiro_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  shared_preferences: ^2.3.2
  path_provider: ^2.1.3

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_cropper: ^11.0.0
  image_picker: ^1.2.0 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - imgs/wellington.jpg
    - imgs/empresa.png

